### PR TITLE
Added additional functions to CustomConsole

### PR DESCRIPTION
**Pull request by sumnerevans**
**Summary**

Addresses #3756. I added the following functions to `CustomConsole`:

- `assert`
- `count`
- `group`
- `groupCollapsed`
- `groupEnd`
- `table`

**Test plan**
I added an automated test for `CustomConsole` at `packages/jest-util/src/__tests__/console.test.js`. This is the output:

```
yarn run jest packages/jest-util/src/__tests__/console.test.js
yarn run v0.27.5
$ node ./packages/jest-cli/bin/jest.js "packages/jest-util/src/__tests__/console.test.js"
 PASS  packages/jest-util/src/__tests__/console.test.js (6.024s)
  CustomConsole
    inherited functions
      ✓ should exist (63ms)
    assert
      ✓ should log the given text if the assertion is false (12ms)
      ✓ should not log the given text if the assertion is true (1ms)
    count
      ✓ should output the number of times count has been called (2ms)
      ✓ should output the number of times count() has been called with a certain label (12ms)
    error/exception
      ✓ should output the error (2ms)
      ✓ should output all of the arguments passed in (23ms)
    group/groupCollapsed/groupEnd
      ✓ should indent the logs one level (3ms)
      ✓ should print the label, if given (1ms)
    info
      ✓ should output the given text (12ms)
      ✓ should output all of the arguments passed in (2ms)
    log
      ✓ should output the given object (89ms)
      ✓ should output all of the arguments passed in (2ms)
    table
      ✓ should output nothing if an object or array is not passed in (2ms)
      ✓ should print an empty table if there are no elements in the object or array (3ms)
      ✓ should print each of the elements of an array on its own line (2ms)
      ✓ should print each of the key-value pairs of an object on its own line (2ms)
    warn
      ✓ should output the given object (9ms)
      ✓ should output all of the arguments passed in (2ms)

Test Suites: 1 passed, 1 total
Tests:       19 passed, 19 total
Snapshots:   0 total
Time:        6.186s
Ran all test suites matching "packages/jest-util/src/__tests__/console.test.js".
Done in 18.82s.

```

### CODE REVIEW

**Comment by sumnerevans** [comment]
@thescientist13 ,

1. Overriding the `_log` function for tests worked. I've added all of the tests and I'm just dealing with some other issues now.
2. I'm not sure why `yarn.lock` changed. It is autogenerated. I just removed it from the commit.

**Comment by thescientist13** [comment]
Awesome work @sumnerevans !

Can you run the build locally and produce a console output of the build running / passing / unit tests passing etc and paste that in here?

**Comment by sumnerevans** [comment]
@thescientist13, done. I had to work through some issues with the Flow typechecker, but I got it working.

**Comment by thescientist13** [comment]
On me to
1. Get Facebook's corporate [CLA](https://code.facebook.com/cla/corporate) signed (cc: @kevinmckenna98 )
1. Rebase latest from master

**Comment by thescientist13** [comment]
@sumnerevans 
Please rebase with master (kenzanlabs)

**Pull request closed without merging**
